### DISCUSSION TITLE
Center value

### DISCUSSION THREAD

**Discussion by phonosys** [sa-si-dev/virtual-select#180] [Q&A] [answered]
is there anyway to center the selected value ? 
padding sucks ;/

**Comment by sa-si-dev** [comment, marked as answer]
Try below css

```css
.vscomp-value {
  text-align: center;
  width: 100%;
}
```
