### DISCUSSION TITLE
Is it possible to enable the horizontal scrollbar

### DISCUSSION THREAD

**Discussion by imnate** [sa-si-dev/virtual-select#213] [Q&A] [answered]
Hi,
Is it possible to enable the horizontal scrollbar when the option content longer then the max weight ?

**Comment by sa-si-dev** [comment, marked as answer]
> Hi,
> Is it possible to enable the horizontal scrollbar when the option content longer then the max weight ?

@imnate As of now, it is not possible in the plugin.

But you can get it by adding the below CSS in your project.

```css
.vscomp-dropbox {
  overflow: auto;
}

.vscomp-search-wrapper,
.vscomp-options-container {
  width: 500px;
}
```
